language: generic

sudo: false

env:
  global:
  - PATH="$HOME/bin:$PATH"

apt:
  packages:
  - unzip

install:
- mkdir -p ~/bin
- ./bin/setup
- if [[ $GCE_JSON ]] ; then
    cat <<EOF > gce.json ;
$GCE_JSON
EOF
    export GOOGLE_ACCOUNT_FILE="$PWD/gce.json" ;
  fi

script:
- terraform get --update
- terraform plan
