language: generic

sudo: false

env:
  global:
  - PATH="$HOME/bin:$PATH"
  - GOOGLE_ACCOUNT_FILE="$TRAVIS_BUILD_DIR/gce.json"

apt:
  packages:
  - unzip

install:
- mkdir -p ~/bin
- ./bin/setup

script:
- terraform get --update
- terraform plan
