language: generic

sudo: false

cache:
  directories:
  - $HOME/bin

env:
  global:
  - PATH="$HOME/bin:$PATH"
  - ENV_GENERATE_CMD="echo NOT REALLY"

apt:
  packages:
  - unzip

install:
- mkdir -p ~/bin
- ./bin/setup

script:
- make clean all
- pushd staging && terraform get --update ; popd
- pushd production && terraform get --update ; popd
- git diff --quiet --exit-code
- git diff --cached --quiet --exit-code
