language: generic

sudo: false

cache:
  directories:
  - $HOME/bin

env:
  global:
  - PATH="$HOME/bin:$PATH"

apt:
  packages:
  - unzip

install:
- mkdir -p ~/bin
- ./bin/setup

script:
- terraform get --update
- terraform plan
