language: generic
sudo: false
env:
  global:
  - PATH="$HOME/bin:$PATH"
apt:
  packages:
  - unzip
install:
- ./bin/setup
- if [[ $GCE_JSON ]] ; then
    echo "$GCE_JSON" > gce.json ;
    export GOOGLE_ACCOUNT_FILE="$PWD/gce.json" ;
  fi
script: terraform plan
